### ISSUE TITLE
Trojan:Win32/Zpevdo.A

### ISSUE THREAD

**Issue by sakurayz** [DrDonk/unlocker#29] opened 2018-10-21 13:17 UTC
Alert level:Severe
Category:Trojan
Details:This program is dangerous and executes commands from an attacker.
Affected items:
file: unlocker301\dumpsmc.exe
file: unlocker301\gettools.exe
file: unlocker301\unlocker.exe

**Comment by MrBananaxx** [comment] 2018-10-21 13:49
It's a false positive. See here : https://github.com/DrDonk/unlocker/issues/20

**Comment by DrDonk** [comment] 2018-10-21 13:50
It's a false postitive caused by PyInstaller runtime. I have recompiled the runtime and it now seems to fix the false positive. It will be in 3.0.2 release.

**Comment by DrDonk** [comment] 2018-10-21 14:01
Just released 3.0.2 so try it out.

**Closed** 2018-10-22 15:28 UTC
