### ISSUE TITLE
4.10: Minor typo bug: darwin.iso copy fails because it is pointing at current directory, not parent directory.

### ISSUE THREAD

**Issue by Warrentheo** [DrDonk/unlocker#7] opened 2022-01-19 17:16 UTC
Minor typo bug: darwin.iso copy fails because it is pointing at current directory, not parent directory.
On windows, running "unlocker.exe install" fails to copy darwin.iso and darwinPre15.iso due to trying to copy them from the 
`./iso/darwin.iso`
`./iso/darwinPre15.iso`
directories...  Needs to be corrected to this instead:
`../iso/darwin.iso`
`../iso/darwinPre15.iso`

**Comment by DrDonk** [comment] 2022-01-19 17:50
Duplicate of https://github.com/DrDonk/golocker/issues/5

**Closed as completed by DrDonk** 2022-01-19 17:50 UTC
Labels: duplicate
